{
  "openapi": "3.1.0",
  "info": {
    "title": "NOX Energy API - Full Control",
    "description": "# Full Control API Documentation\n\nThis documentation shows only the endpoints available to full control users.\n\n## Authentication\n\n1. Get your API key from [NOX Energy](mailto:support@nox.energy).\n2. Include the API key in your API calls with the header: `x-api-key: YOUR_API_KEY`.\n\n## Access Level\n\nThis documentation is specifically for **full control users** who have access to these endpoints.\n\nBase URL: [https://api.nox.energy](https://api.nox.energy)\n",
    "version": "1.0.0"
  },
  "paths": {
    "/v1/devices": {
      "get": {
        "tags": [
          "Asset Info"
        ],
        "summary": "Get Devices",
        "description": "Get information about all NOX connected devices associated with your energy supplier account. If you want to know the response structure or possible enum values, like steerable reasons, you can check it in the response model `schema`.",
        "operationId": "get_devices_v1_devices_get",
        "parameters": [
          {
            "name": "limit",
            "in": "query",
            "required": false,
            "schema": {
              "type": "integer",
              "maximum": 4000,
              "minimum": 1,
              "description": "\nThe maximum number of items to return per page of results.\n\nThis should be used together with the `next_token` parameter to paginate through results.\n\nRead the pagination parameter documentation for more details.\n",
              "default": 1000,
              "title": "Limit"
            },
            "description": "\nThe maximum number of items to return per page of results.\n\nThis should be used together with the `next_token` parameter to paginate through results.\n\nRead the pagination parameter documentation for more details.\n"
          },
          {
            "name": "steerable_status",
            "in": "query",
            "required": false,
            "schema": {
              "type": "boolean",
              "description": "\nIf `true`, return only data related to the device's current steerable status.\n\nIf `false` or not given, return all available device data including its status.\n",
              "default": false,
              "title": "Steerable Status"
            },
            "description": "\nIf `true`, return only data related to the device's current steerable status.\n\nIf `false` or not given, return all available device data including its status.\n"
          },
          {
            "name": "steering_enabled",
            "in": "query",
            "required": false,
            "schema": {
              "type": "boolean",
              "description": "\nIf `true`, return only data related to the device's which has `steering_enabled` = `true`.\n\nIf `false` or not given, do not filter on `steering_enabled` field.\n",
              "default": false,
              "title": "Steering Enabled"
            },
            "description": "\nIf `true`, return only data related to the device's which has `steering_enabled` = `true`.\n\nIf `false` or not given, do not filter on `steering_enabled` field.\n"
          },
          {
            "name": "steerable",
            "in": "query",
            "required": false,
            "schema": {
              "type": "boolean",
              "description": "\nIf `true`, return only data related to the device's which has `steerable` = `true`.\n\nIf `false` or not given, do not filter on `steerable` field.\n",
              "default": false,
              "title": "Steerable"
            },
            "description": "\nIf `true`, return only data related to the device's which has `steerable` = `true`.\n\nIf `false` or not given, do not filter on `steerable` field.\n"
          },
          {
            "name": "next_token",
            "in": "query",
            "required": false,
            "schema": {
              "anyOf": [
                {
                  "type": "string"
                },
                {
                  "type": "null"
                }
              ],
              "description": "\nThe `next_token` is a token used to retrieve the next page of results when there are more results\nthan can fit in a single page(=API response).\n\nBy default, the API will return a `next_token` of the first page if no token was given as a parameter.\n\nIf the token is `null` you have reached the end of the results.\n\nThis should be used together with the `limit` parameter to paginate through results.\n\n\n\nTo get all results of your call, you can keep calling the same API call with the previously returned `next_token` until it returns `null`.\n",
              "title": "Next Token"
            },
            "description": "\nThe `next_token` is a token used to retrieve the next page of results when there are more results\nthan can fit in a single page(=API response).\n\nBy default, the API will return a `next_token` of the first page if no token was given as a parameter.\n\nIf the token is `null` you have reached the end of the results.\n\nThis should be used together with the `limit` parameter to paginate through results.\n\n\n\nTo get all results of your call, you can keep calling the same API call with the previously returned `next_token` until it returns `null`.\n"
          },
          {
            "name": "device_id",
            "in": "query",
            "required": false,
            "schema": {
              "anyOf": [
                {
                  "type": "string"
                },
                {
                  "type": "null"
                }
              ],
              "description": "\nThe ID of the device to filter on. If not provided, all devices are returned.\n",
              "title": "Device Id"
            },
            "description": "\nThe ID of the device to filter on. If not provided, all devices are returned.\n"
          },
          {
            "name": "user_id",
            "in": "query",
            "required": false,
            "schema": {
              "anyOf": [
                {
                  "type": "string"
                },
                {
                  "type": "null"
                }
              ],
              "description": "\nThe ID of the user to filter on. If not provided, all users are returned.\n",
              "title": "User Id"
            },
            "description": "\nThe ID of the user to filter on. If not provided, all users are returned.\n"
          },
          {
            "name": "needs_reauthentication",
            "in": "query",
            "required": false,
            "schema": {
              "anyOf": [
                {
                  "type": "boolean"
                },
                {
                  "type": "null"
                }
              ],
              "description": "\nIf `True`, filter devices that need reauthentication.\n",
              "default": false,
              "title": "Needs Reauthentication"
            },
            "description": "\nIf `True`, filter devices that need reauthentication.\n"
          },
          {
            "name": "learning_period_ended",
            "in": "query",
            "required": false,
            "schema": {
              "anyOf": [
                {
                  "type": "boolean"
                },
                {
                  "type": "null"
                }
              ],
              "description": "\nIf `True`, filter devices for which the learning period of gathering data has ended. \n\nIf `False`, filter devices for which the learning period of gathering data has not ended. \n\nIf `None`, do not filter based on learning period status. \n\n",
              "title": "Learning Period Ended"
            },
            "description": "\nIf `True`, filter devices for which the learning period of gathering data has ended. \n\nIf `False`, filter devices for which the learning period of gathering data has not ended. \n\nIf `None`, do not filter based on learning period status. \n\n"
          },
          {
            "name": "has_delayed_power_data_1d",
            "in": "query",
            "required": false,
            "schema": {
              "anyOf": [
                {
                  "type": "boolean"
                },
                {
                  "type": "null"
                }
              ],
              "description": "\nIf `True`, filter devices that have delayed power data by 1 day for the previous day. This means that the power data of the previous day is only updated between 2-4 AM UTC on a daily basis for the full previous day. \n\nIf `False`, filter devices that do not have delayed power data by 1 day for the previous day but instead provide real-time power data. \n\nIf `None`, do not filter based on whether devices have delayed power data by 1 day for the previous day. \n\n",
              "title": "Has Delayed Power Data 1D"
            },
            "description": "\nIf `True`, filter devices that have delayed power data by 1 day for the previous day. This means that the power data of the previous day is only updated between 2-4 AM UTC on a daily basis for the full previous day. \n\nIf `False`, filter devices that do not have delayed power data by 1 day for the previous day but instead provide real-time power data. \n\nIf `None`, do not filter based on whether devices have delayed power data by 1 day for the previous day. \n\n"
          },
          {
            "name": "model_type",
            "in": "query",
            "required": false,
            "schema": {
              "anyOf": [
                {
                  "type": "string"
                },
                {
                  "type": "null"
                }
              ],
              "description": "\nThe model type to filter on, e.g. 'ata', 'atw', 'wtw'. If None, do not filter on model type.\n",
              "title": "Model Type"
            },
            "description": "\nThe model type to filter on, e.g. 'ata', 'atw', 'wtw'. If None, do not filter on model type.\n"
          },
          {
            "name": "has_cooling",
            "in": "query",
            "required": false,
            "schema": {
              "anyOf": [
                {
                  "type": "boolean"
                },
                {
                  "type": "null"
                }
              ],
              "description": "\nIf `True`, filter devices that have cooling capabilities. \n\nIf `False`, filter devices that do not have cooling capabilities. \n\nIf `None`, do not filter based on cooling capabilities. \n\n",
              "title": "Has Cooling"
            },
            "description": "\nIf `True`, filter devices that have cooling capabilities. \n\nIf `False`, filter devices that do not have cooling capabilities. \n\nIf `None`, do not filter based on cooling capabilities. \n\n"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response for thermal-control API",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DevicesResponse"
                },
                "example": {
                  "data": [
                    {
                      "model": "model_g",
                      "model_type": "atw",
                      "brand": "nibe",
                      "country": "BE",
                      "device_id": "01a5c222-5b76-4531-b587-5deeb81a3db3",
                      "user_id": "user_4",
                      "device_type": "heat_pump",
                      "has_delayed_power_data_1d": true,
                      "legionella_config": {
                        "frequency_per_weeks": 1,
                        "capacity": 20,
                        "room_min_cycle_time": 15,
                        "dhw_min_cycle_time": 30,
                        "duration_minutes": 60
                      },
                      "cycle_config": {
                        "max_cycles_per_day": 8,
                        "dhw_max_cycle_time": 120.0
                      },
                      "steerable_status": {
                        "steering_enabled": true,
                        "steerable": true,
                        "DHW": {
                          "can_activate_action": true,
                          "in_active_action": false,
                          "reason": "Device is ready to receive an action."
                        },
                        "room": {
                          "can_activate_action": true,
                          "in_active_action": false,
                          "reason": "Device is ready to receive an action."
                        }
                      },
                      "needs_reauthentication": false,
                      "has_cooling": true
                    },
                    {
                      "model": "model_b",
                      "model_type": "atw",
                      "brand": "nibe",
                      "device_id": "01bbbaab-159a-4898-bcba-d81acdb2353c",
                      "user_id": "user_5",
                      "device_type": "heat_pump",
                      "has_delayed_power_data_1d": false,
                      "legionella_config": {
                        "frequency_per_weeks": 2,
                        "capacity": 20,
                        "duration_minutes": 60
                      },
                      "cycle_config": {
                        "max_cycles_per_day": 6,
                        "room_min_cycle_time": 15,
                        "dhw_min_cycle_time": 30,
                        "dhw_max_cycle_time": 60.0
                      },
                      "steerable_status": {
                        "steering_enabled": true,
                        "steerable": true,
                        "DHW": {
                          "can_activate_action": true,
                          "in_active_action": false,
                          "reason": "Device is ready to receive an action."
                        },
                        "room": {
                          "can_activate_action": true,
                          "in_active_action": false,
                          "reason": "Device is ready to receive an action."
                        }
                      },
                      "needs_reauthentication": false,
                      "has_cooling": false
                    }
                  ],
                  "meta": {
                    "energy_supplier": "Energy Supplier A",
                    "capacity_unit": "kWh",
                    "next_token": "eyJkZXZpY2VfaWQiOiAiMDFiYmJhYWItMTU5YS00ODk4LWJjYmEtZDgxYWNkYjIzNTNjIiwgImVuZXJneV9zdXBwbGllciI6ICJFbmVyZ3kgU3VwcGxpZXIgQSJ9",
                    "cycle_time_units": "minutes"
                  }
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          }
        }
      }
    },
    "/v1/device/consumption/forecast/historical": {
      "get": {
        "tags": [
          "Device Consumption"
        ],
        "summary": "Get Device Consumption Forecast Historical",
        "description": "Get the forecasted consumption for devices associated with your energy supplier account in kWh for a specific timeframe with 15min granularity.\n\n This forecast is done everyday at a fixed time depending on supplier.\n\n The timestamp refers to the data that will happenin the next 15 minutes after the timestamp.",
        "operationId": "get_device_consumption_forecast_historical_v1_device_consumption_forecast_historical_get",
        "parameters": [
          {
            "name": "start_time",
            "in": "query",
            "required": true,
            "schema": {
              "type": "string",
              "description": "\nStart time when the consumption measurement were taken.\nThe time is in UTC in ISO 8601 format.\n\n\n\nTime format examples:\n- 2023-10-01T00:00:00Z\n- 2023-10-01T00:00:00\n",
              "title": "Start Time"
            },
            "description": "\nStart time when the consumption measurement were taken.\nThe time is in UTC in ISO 8601 format.\n\n\n\nTime format examples:\n- 2023-10-01T00:00:00Z\n- 2023-10-01T00:00:00\n"
          },
          {
            "name": "end_time",
            "in": "query",
            "required": true,
            "schema": {
              "type": "string",
              "description": "\nEnd time when the consumption measurement were taken.\nThe time is in UTC in ISO 8601 format.\n\n\n\nTime format examples:\n- 2023-10-01T00:00:00Z\n- 2023-10-01T00:00:00\n",
              "title": "End Time"
            },
            "description": "\nEnd time when the consumption measurement were taken.\nThe time is in UTC in ISO 8601 format.\n\n\n\nTime format examples:\n- 2023-10-01T00:00:00Z\n- 2023-10-01T00:00:00\n"
          },
          {
            "name": "limit",
            "in": "query",
            "required": false,
            "schema": {
              "type": "integer",
              "maximum": 1000,
              "minimum": 1,
              "description": "\nThe maximum number of items to return per page of results.\n\nThis should be used together with the `next_token` parameter to paginate through results.\n\nRead the pagination parameter documentation for more details.\n",
              "default": 1000,
              "title": "Limit"
            },
            "description": "\nThe maximum number of items to return per page of results.\n\nThis should be used together with the `next_token` parameter to paginate through results.\n\nRead the pagination parameter documentation for more details.\n"
          },
          {
            "name": "next_token",
            "in": "query",
            "required": false,
            "schema": {
              "anyOf": [
                {
                  "type": "string"
                },
                {
                  "type": "null"
                }
              ],
              "description": "\nThe `next_token` is a token used to retrieve the next page of results when there are more results\nthan can fit in a single page(=API response).\n\nBy default, the API will return a `next_token` of the first page if no token was given as a parameter.\n\nIf the token is `null` you have reached the end of the results.\n\nThis should be used together with the `limit` parameter to paginate through results.\n\n\n\nTo get all results of your call, you can keep calling the same API call with the previously returned `next_token` until it returns `null`.\n",
              "title": "Next Token"
            },
            "description": "\nThe `next_token` is a token used to retrieve the next page of results when there are more results\nthan can fit in a single page(=API response).\n\nBy default, the API will return a `next_token` of the first page if no token was given as a parameter.\n\nIf the token is `null` you have reached the end of the results.\n\nThis should be used together with the `limit` parameter to paginate through results.\n\n\n\nTo get all results of your call, you can keep calling the same API call with the previously returned `next_token` until it returns `null`.\n"
          },
          {
            "name": "aggregated",
            "in": "query",
            "required": false,
            "schema": {
              "type": "boolean",
              "description": "\nIf `true`, sum the consumption of the devices.\n\nIf `false`, return the consumption of each device separately.\n\n**Note**: If `device_id` is given in the device_id parameter, the aggregated parameter is ignored.\n",
              "default": false,
              "title": "Aggregated"
            },
            "description": "\nIf `true`, sum the consumption of the devices.\n\nIf `false`, return the consumption of each device separately.\n\n**Note**: If `device_id` is given in the device_id parameter, the aggregated parameter is ignored.\n"
          },
          {
            "name": "device_id",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string",
              "description": "\nDevice ID to get consumption of. If `None`, all devices are included.\n",
              "title": "Device Id"
            },
            "description": "\nDevice ID to get consumption of. If `None`, all devices are included.\n"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "additionalProperties": true,
                  "title": "Response Get Device Consumption Forecast Historical V1 Device Consumption Forecast Historical Get"
                },
                "example": {
                  "data": [
                    {
                      "forecast_time": "2025-05-01 07:45",
                      "device_id": "1400d85b-47c3-49e1-9317-ae1bfccb635c",
                      "consumption": "2.61",
                      "supplier_user_id": "1234"
                    },
                    {
                      "forecast_time": "2025-05-01 07:45",
                      "device_id": "0910947a-fab9-450e-b5ac-48e9c4f3e725",
                      "consumption": "1.75",
                      "supplier_user_id": "12345"
                    }
                  ],
                  "meta": {
                    "energy_supplier": "Energy Supplier A",
                    "next_token": "AYABeH50-To0SRdAWC9BY9aCIaEAAAABAAdhd3Mta21zAE5hcm46YXdzOmttczpldS1jZW50cmFsLTE6ND",
                    "consumption_unit": "kWh",
                    "granularity": "15min",
                    "output_timezone": "UTC"
                  }
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          }
        }
      }
    },
    "/v1/device/typical-consumption/historical": {
      "get": {
        "tags": [
          "Device Consumption"
        ],
        "summary": "Get Device Typical Consumption Historical",
        "description": "Get the typical consumption for devices associated with your energy supplier account in kWh for a specific timeframe with 15min granularity.\n\n This estimation is done everyday at a fixed time depending on supplier.\n\n The timestamp refers to the data that will happenin the next 15 minutes after the timestamp.",
        "operationId": "get_device_typical_consumption_historical_v1_device_typical_consumption_historical_get",
        "parameters": [
          {
            "name": "start_time",
            "in": "query",
            "required": true,
            "schema": {
              "type": "string",
              "description": "\nStart time when the consumption measurement were taken.\nThe time is in UTC in ISO 8601 format.\n\n\n\nTime format examples:\n- 2023-10-01T00:00:00Z\n- 2023-10-01T00:00:00\n",
              "title": "Start Time"
            },
            "description": "\nStart time when the consumption measurement were taken.\nThe time is in UTC in ISO 8601 format.\n\n\n\nTime format examples:\n- 2023-10-01T00:00:00Z\n- 2023-10-01T00:00:00\n"
          },
          {
            "name": "end_time",
            "in": "query",
            "required": true,
            "schema": {
              "type": "string",
              "description": "\nEnd time when the consumption measurement were taken.\nThe time is in UTC in ISO 8601 format.\n\n\n\nTime format examples:\n- 2023-10-01T00:00:00Z\n- 2023-10-01T00:00:00\n",
              "title": "End Time"
            },
            "description": "\nEnd time when the consumption measurement were taken.\nThe time is in UTC in ISO 8601 format.\n\n\n\nTime format examples:\n- 2023-10-01T00:00:00Z\n- 2023-10-01T00:00:00\n"
          },
          {
            "name": "limit",
            "in": "query",
            "required": false,
            "schema": {
              "type": "integer",
              "maximum": 1000,
              "minimum": 1,
              "description": "\nThe maximum number of items to return per page of results.\n\nThis should be used together with the `next_token` parameter to paginate through results.\n\nRead the pagination parameter documentation for more details.\n",
              "default": 1000,
              "title": "Limit"
            },
            "description": "\nThe maximum number of items to return per page of results.\n\nThis should be used together with the `next_token` parameter to paginate through results.\n\nRead the pagination parameter documentation for more details.\n"
          },
          {
            "name": "next_token",
            "in": "query",
            "required": false,
            "schema": {
              "anyOf": [
                {
                  "type": "string"
                },
                {
                  "type": "null"
                }
              ],
              "description": "\nThe `next_token` is a token used to retrieve the next page of results when there are more results\nthan can fit in a single page(=API response).\n\nBy default, the API will return a `next_token` of the first page if no token was given as a parameter.\n\nIf the token is `null` you have reached the end of the results.\n\nThis should be used together with the `limit` parameter to paginate through results.\n\n\n\nTo get all results of your call, you can keep calling the same API call with the previously returned `next_token` until it returns `null`.\n",
              "title": "Next Token"
            },
            "description": "\nThe `next_token` is a token used to retrieve the next page of results when there are more results\nthan can fit in a single page(=API response).\n\nBy default, the API will return a `next_token` of the first page if no token was given as a parameter.\n\nIf the token is `null` you have reached the end of the results.\n\nThis should be used together with the `limit` parameter to paginate through results.\n\n\n\nTo get all results of your call, you can keep calling the same API call with the previously returned `next_token` until it returns `null`.\n"
          },
          {
            "name": "aggregated",
            "in": "query",
            "required": false,
            "schema": {
              "type": "boolean",
              "description": "\nIf `true`, sum the consumption of the devices.\n\nIf `false`, return the consumption of each device separately.\n\n**Note**: If `device_id` is given in the device_id parameter, the aggregated parameter is ignored.\n",
              "default": false,
              "title": "Aggregated"
            },
            "description": "\nIf `true`, sum the consumption of the devices.\n\nIf `false`, return the consumption of each device separately.\n\n**Note**: If `device_id` is given in the device_id parameter, the aggregated parameter is ignored.\n"
          },
          {
            "name": "device_id",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string",
              "description": "\nDevice ID to get consumption of. If `None`, all devices are included.\n",
              "title": "Device Id"
            },
            "description": "\nDevice ID to get consumption of. If `None`, all devices are included.\n"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "additionalProperties": true,
                  "title": "Response Get Device Typical Consumption Historical V1 Device Typical Consumption Historical Get"
                },
                "example": {
                  "data": [
                    {
                      "typical_consumption_time": "2025-04-29 16:00",
                      "device_id": "0910947a-fab9-450e-b5ac-48e9c4f3e725",
                      "consumption": "2.88",
                      "supplier_user_id": "1234"
                    },
                    {
                      "typical_consumption_time": "2025-04-29 16:00",
                      "device_id": "1400d85b-47c3-49e1-9317-ae1bfccb635c",
                      "consumption": "1.16",
                      "supplier_user_id": "1234"
                    }
                  ],
                  "meta": {
                    "energy_supplier": "Energy Supplier A",
                    "next_token": "AYABeH50-To0SRdAWC9BY9aCIaEAAAABAAdhd3Mta21zAE5hcm46YXdzOmttczpldS1jZW50cmFsLTE6NDQxMjA5Mzg3MTExOmtleS80Yzk3N2IxMi02NDA4LTRhNzktYWIyMy1hZTk0Y2Y0YTFmZjQAuAECAQB4KL0",
                    "consumption_unit": "kWh",
                    "granularity": "15min",
                    "output_timezone": "UTC"
                  }
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          }
        }
      }
    },
    "/v1/device/thermal-control/settings": {
      "post": {
        "tags": [
          "Thermal Control"
        ],
        "summary": "Submit Thermal Control Settings",
        "description": "Update on a device or user level the device/user settings. If you want to update a setting on a device level, provide the device_id along with the user_id.\n\n You can change the following settings:\n\n * The lower and upper comfort temperature bounds of\n end users/devices in degrees celcius.\n\n * Enable/Disable steering in boolean.\n\n * The country code and the postal code",
        "operationId": "submit_thermal_control_settings_v1_device_thermal_control_settings_post",
        "parameters": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "additionalProperties": true,
                "title": "Request Body"
              },
              "examples": {
                "settings_example": {
                  "summary": "Example of thermal control settings submission",
                  "value": {
                    "user_id": "01910947a-fab9-450e-b5ac-48e9c4f3e725",
                    "room": {
                      "temperature_upper_bound": 1.0,
                      "temperature_lower_bound": 1.5
                    },
                    "steering_enabled": {
                      "heat_pump": true
                    },
                    "location": {
                      "country": "BE",
                      "postal_code": "3500"
                    }
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "additionalProperties": true,
                  "title": "Response Submit Thermal Control Settings V1 Device Thermal Control Settings Post"
                },
                "example": {
                  "status": "success",
                  "message": "Settings updated successfully.",
                  "meta": {
                    "energy_supplier": "Energy Supplier A"
                  }
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          }
        }
      }
    },
    "/v1/device/consumption/historical": {
      "get": {
        "tags": [
          "Device Consumption"
        ],
        "summary": "Get Device Consumption Historical",
        "description": "Get the measured historical consumption data for devices associated with your energy supplier account in kWh for a specific timeframe in 15min granularity.\n\n Our example timeframe might be outside this range.\n\n The timestamp refers to the data that will happenin the next 15 minutes after the timestamp.",
        "operationId": "get_device_consumption_historical_v1_device_consumption_historical_get",
        "parameters": [
          {
            "name": "start_time",
            "in": "query",
            "required": true,
            "schema": {
              "type": "string",
              "description": "\nStart time when the consumption measurement were taken.\nThe time is in UTC in ISO 8601 format.\n\n\n\nTime format examples:\n- 2023-10-01T00:00:00Z\n- 2023-10-01T00:00:00\n",
              "title": "Start Time"
            },
            "description": "\nStart time when the consumption measurement were taken.\nThe time is in UTC in ISO 8601 format.\n\n\n\nTime format examples:\n- 2023-10-01T00:00:00Z\n- 2023-10-01T00:00:00\n"
          },
          {
            "name": "end_time",
            "in": "query",
            "required": true,
            "schema": {
              "type": "string",
              "description": "\nEnd time when the consumption measurement were taken.\nThe time is in UTC in ISO 8601 format.\n\n\n\nTime format examples:\n- 2023-10-01T00:00:00Z\n- 2023-10-01T00:00:00\n",
              "title": "End Time"
            },
            "description": "\nEnd time when the consumption measurement were taken.\nThe time is in UTC in ISO 8601 format.\n\n\n\nTime format examples:\n- 2023-10-01T00:00:00Z\n- 2023-10-01T00:00:00\n"
          },
          {
            "name": "limit",
            "in": "query",
            "required": false,
            "schema": {
              "type": "integer",
              "maximum": 1000,
              "minimum": 1,
              "description": "\nThe maximum number of items to return per page of results.\n\nThis should be used together with the `next_token` parameter to paginate through results.\n\nRead the pagination parameter documentation for more details.\n",
              "default": 1000,
              "title": "Limit"
            },
            "description": "\nThe maximum number of items to return per page of results.\n\nThis should be used together with the `next_token` parameter to paginate through results.\n\nRead the pagination parameter documentation for more details.\n"
          },
          {
            "name": "next_token",
            "in": "query",
            "required": false,
            "schema": {
              "anyOf": [
                {
                  "type": "string"
                },
                {
                  "type": "null"
                }
              ],
              "description": "\nThe `next_token` is a token used to retrieve the next page of results when there are more results\nthan can fit in a single page(=API response).\n\nBy default, the API will return a `next_token` of the first page if no token was given as a parameter.\n\nIf the token is `null` you have reached the end of the results.\n\nThis should be used together with the `limit` parameter to paginate through results.\n\n\n\nTo get all results of your call, you can keep calling the same API call with the previously returned `next_token` until it returns `null`.\n",
              "title": "Next Token"
            },
            "description": "\nThe `next_token` is a token used to retrieve the next page of results when there are more results\nthan can fit in a single page(=API response).\n\nBy default, the API will return a `next_token` of the first page if no token was given as a parameter.\n\nIf the token is `null` you have reached the end of the results.\n\nThis should be used together with the `limit` parameter to paginate through results.\n\n\n\nTo get all results of your call, you can keep calling the same API call with the previously returned `next_token` until it returns `null`.\n"
          },
          {
            "name": "aggregated",
            "in": "query",
            "required": false,
            "schema": {
              "type": "boolean",
              "description": "\nIf `true`, sum the consumption of the devices.\n\nIf `false`, return the consumption of each device separately.\n\n**Note**: If `device_id` is given in the device_id parameter, the aggregated parameter is ignored.\n",
              "default": false,
              "title": "Aggregated"
            },
            "description": "\nIf `true`, sum the consumption of the devices.\n\nIf `false`, return the consumption of each device separately.\n\n**Note**: If `device_id` is given in the device_id parameter, the aggregated parameter is ignored.\n"
          },
          {
            "name": "device_id",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string",
              "description": "\nDevice ID to get consumption of. If `None`, all devices are included.\n",
              "title": "Device Id"
            },
            "description": "\nDevice ID to get consumption of. If `None`, all devices are included.\n"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "additionalProperties": true,
                  "title": "Response Get Device Consumption Historical V1 Device Consumption Historical Get"
                },
                "example": {
                  "data": [
                    {
                      "measurement_time": "2025-04-29 16:00",
                      "device_id": "0910947a-fab9-450e-b5ac-48e9c4f3e725",
                      "consumption": "2.88",
                      "supplier_user_id": "1234"
                    },
                    {
                      "measurement_time": "2025-04-29 16:00",
                      "device_id": "1400d85b-47c3-49e1-9317-ae1bfccb635c",
                      "consumption": "1.16",
                      "supplier_user_id": "12345"
                    }
                  ],
                  "meta": {
                    "energy_supplier": "Energy Supplier A",
                    "next_token": "AYABeH50-To0SRdAWC9BY9aCIaEAAAABAAdhd3Mta21zAE5hcm46YXdzOmttczpldS1jZW50cmFsLTE6NDQxMjA5Mzg3MTExOmtleS80Yzk3N2IxMi02NDA4LTRhNzktYWIyMy1hZTk0Y2Y0YTFmZjQAuAECAQB4KL0",
                    "consumption_unit": "kWh",
                    "granularity": "15min",
                    "output_timezone": "UTC"
                  }
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          }
        }
      }
    },
    "/v1/user": {
      "delete": {
        "tags": [
          "User Management"
        ],
        "summary": "Delete User",
        "description": "Delete all data and connections associated to the user and the energy supplier. Some delete operations might be delayed by 1 day.",
        "operationId": "delete_user_v1_user_delete",
        "parameters": [
          {
            "name": "user_id",
            "in": "query",
            "required": true,
            "schema": {
              "type": "string",
              "description": "\nNox User ID of the user to delete all associated data for.\n",
              "title": "User Id"
            },
            "description": "\nNox User ID of the user to delete all associated data for.\n"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "additionalProperties": true,
                  "title": "Response Delete User V1 User Delete"
                },
                "example": {
                  "status": "success",
                  "message": "User 1234578 deleted successfully.",
                  "meta": {
                    "energy_supplier": [
                      "Energy Supplier A"
                    ]
                  }
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "ActionStatus": {
        "properties": {
          "can_activate_action": {
            "anyOf": [
              {
                "type": "boolean"
              },
              {
                "type": "null"
              }
            ],
            "title": "Can Activate Action",
            "description": "Whether action can be activated"
          },
          "in_active_action": {
            "anyOf": [
              {
                "type": "boolean"
              },
              {
                "type": "null"
              }
            ],
            "title": "In Active Action",
            "description": "Whether currently in active action"
          },
          "reason": {
            "anyOf": [
              {
                "$ref": "#/components/schemas/Reason"
              },
              {
                "type": "null"
              }
            ],
            "description": "Reason for the current status"
          }
        },
        "type": "object",
        "title": "ActionStatus",
        "description": "Action status for device components."
      },
      "CycleConfig": {
        "properties": {
          "max_cycles_per_day": {
            "anyOf": [
              {
                "type": "integer"
              },
              {
                "type": "null"
              }
            ],
            "title": "Max Cycles Per Day",
            "description": "Maximum cycles allowed per day"
          },
          "room_min_cycle_time": {
            "anyOf": [
              {
                "type": "integer"
              },
              {
                "type": "null"
              }
            ],
            "title": "Room Min Cycle Time",
            "description": "Minimum cycle time for room heating in minutes, if applicable."
          },
          "dhw_min_cycle_time": {
            "anyOf": [
              {
                "type": "integer"
              },
              {
                "type": "null"
              }
            ],
            "title": "Dhw Min Cycle Time",
            "description": "Minimum cycle time for DHW in minutes, if applicable."
          },
          "dhw_max_cycle_time": {
            "anyOf": [
              {
                "type": "integer"
              },
              {
                "type": "null"
              }
            ],
            "title": "Dhw Max Cycle Time",
            "description": "Maximum cycle time for DHW in minutes, if applicable."
          }
        },
        "type": "object",
        "title": "CycleConfig",
        "description": "Cycle configuration model."
      },
      "Device": {
        "properties": {
          "model": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Model",
            "description": "Device model"
          },
          "model_type": {
            "anyOf": [
              {
                "$ref": "#/components/schemas/ModelType"
              },
              {
                "type": "null"
              }
            ],
            "description": "Device model type such as (Air to Air Heat Pump, Air to Water Heat Pump, Water to Water Heat Pump)"
          },
          "brand": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Brand",
            "description": "Device brand"
          },
          "country": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Country",
            "description": "Country code"
          },
          "device_id": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Device Id",
            "description": "Unique device identifier"
          },
          "user_id": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "User Id",
            "description": "User identifier"
          },
          "device_type": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Device Type",
            "description": "Type of device"
          },
          "has_delayed_power_data_1d": {
            "anyOf": [
              {
                "type": "boolean"
              },
              {
                "type": "null"
              }
            ],
            "title": "Has Delayed Power Data 1D",
            "description": "Whether the device has delayed power data by 1 day for the previous day. This power data is updated between 2-4 AM UTC on a daily basis for the full previous day."
          },
          "legionella_config": {
            "anyOf": [
              {
                "$ref": "#/components/schemas/LegionellaConfig"
              },
              {
                "type": "null"
              }
            ],
            "description": "Legionella prevention configuration"
          },
          "cycle_config": {
            "anyOf": [
              {
                "$ref": "#/components/schemas/CycleConfig"
              },
              {
                "type": "null"
              }
            ],
            "description": "Cycle configuration"
          },
          "steerable_status": {
            "anyOf": [
              {
                "$ref": "#/components/schemas/SteerableStatus"
              },
              {
                "type": "null"
              }
            ],
            "description": "Device steering status"
          },
          "needs_reauthentication": {
            "anyOf": [
              {
                "type": "boolean"
              },
              {
                "type": "null"
              }
            ],
            "title": "Needs Reauthentication",
            "description": "Whether the device needs reauthentication"
          }
        },
        "type": "object",
        "title": "Device",
        "description": "Device information model."
      },
      "DevicesMeta": {
        "properties": {
          "energy_supplier": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Energy Supplier",
            "description": "Energy supplier name"
          },
          "capacity_unit": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Capacity Unit",
            "description": "Unit for capacity measurements"
          },
          "next_token": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Next Token",
            "description": "Token for pagination"
          },
          "cycle_time_units": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Cycle Time Units",
            "description": "Unit for MAX or MIN cycle times. Which is the amount of minutes a unit can be active for that purpose."
          }
        },
        "type": "object",
        "title": "DevicesMeta",
        "description": "Metadata for devices response."
      },
      "DevicesResponse": {
        "properties": {
          "data": {
            "anyOf": [
              {
                "items": {
                  "$ref": "#/components/schemas/Device"
                },
                "type": "array"
              },
              {
                "type": "null"
              }
            ],
            "title": "Data",
            "description": "List of devices"
          },
          "meta": {
            "anyOf": [
              {
                "$ref": "#/components/schemas/DevicesMeta"
              },
              {
                "type": "null"
              }
            ],
            "description": "Response metadata"
          }
        },
        "type": "object",
        "title": "DevicesResponse",
        "description": "Response model for devices endpoint."
      },
      "GeneralReason": {
        "type": "string",
        "enum": [
          "Heat pump connected recently, still collecting data to improve models.",
          "Processing error, please contact support.",
          "Device disconnected, it might reconnect later or be permanently be disconnected.",
          "Device in error state. Might recover automatically later.",
          "User settings prevent steering.",
          "Holiday mode active, steering disabled or blocked by device.",
          "Device is turned off, steering disabled or blocked by device.",
          "Device is unsupported brand/model, will be supported in future updates.",
          "Device is unsupported model, will not be supported in future updates.",
          "Air to Air Heat pumps not supported for this brand yet.",
          "Air to Water Heat pumps not supported for this brand yet.",
          "Water to Water Heat pumps not supported for this brand yet.",
          "Device gateway model does not allow steering.",
          "Important data missing, this might improve with future updates.",
          "Important data missing, will not be supported in future updates.",
          "Unauthorized country, steering not allowed in this country.",
          "Reauthentication required.",
          "Unknown reason, please contact support."
        ],
        "title": "GeneralReason",
        "description": "Enumeration for general reasons."
      },
      "HTTPValidationError": {
        "properties": {
          "detail": {
            "items": {
              "$ref": "#/components/schemas/ValidationError"
            },
            "type": "array",
            "title": "Detail"
          }
        },
        "type": "object",
        "title": "HTTPValidationError"
      },
      "LegionellaConfig": {
        "properties": {
          "frequency_per_weeks": {
            "anyOf": [
              {
                "type": "integer"
              },
              {
                "type": "null"
              }
            ],
            "title": "Frequency Per Weeks",
            "description": "Frequency per weeks for legionella prevention"
          },
          "capacity": {
            "anyOf": [
              {
                "type": "number"
              },
              {
                "type": "null"
              }
            ],
            "title": "Capacity",
            "description": "Capacity for legionella prevention"
          },
          "duration_minutes": {
            "anyOf": [
              {
                "type": "integer"
              },
              {
                "type": "null"
              }
            ],
            "title": "Duration Minutes",
            "description": "Duration in minutes for legionella prevention"
          }
        },
        "type": "object",
        "title": "LegionellaConfig",
        "description": "Legionella configuration model."
      },
      "ModelType": {
        "type": "string",
        "enum": [
          "ata",
          "atw",
          "wtw"
        ],
        "title": "ModelType",
        "description": "Enumeration for model types."
      },
      "Reason": {
        "type": "string",
        "enum": [
          "No flexibility available based on current device state.",
          "Cycle constraints prevent a new action at this time.",
          "Cycle constraints forced stop of current cycle.",
          "No DHW control available on this device.",
          "No room control available on this device.",
          "Outside comfort band, Nox takes over until within comfort.",
          "No schedule available, Nox takes over to assure comfort.",
          "Can receive actions.",
          "Early activation command send to device, following DHW tank schedule.",
          "DHW tank active, following DHW tank schedule.",
          "Early deactivation command send to device, following DHW tank schedule.",
          "Early activation command send to device, following room heating/cooling schedule.",
          "Room heating/cooling active, following room heating/cooling schedule.",
          "Early deactivation command send to device, following room heating/cooling schedule.",
          "Room schedule not writable and enabled, ask end user to disable it.",
          "Uncertain heat pump activity, waiting for more data.",
          "Processing error, please contact support."
        ],
        "title": "Reason",
        "description": "Enumeration for reasons."
      },
      "SteerableStatus": {
        "properties": {
          "steering_enabled": {
            "anyOf": [
              {
                "type": "boolean"
              },
              {
                "type": "null"
              }
            ],
            "title": "Steering Enabled",
            "description": "Whether steering is enabled"
          },
          "steerable": {
            "anyOf": [
              {
                "type": "boolean"
              },
              {
                "type": "null"
              }
            ],
            "title": "Steerable",
            "description": "Whether device is steerable"
          },
          "learning_period_ended": {
            "anyOf": [
              {
                "type": "boolean"
              },
              {
                "type": "null"
              }
            ],
            "title": "Learning Period Ended",
            "description": "Whether the learning period has ended"
          },
          "general_reason": {
            "anyOf": [
              {
                "$ref": "#/components/schemas/GeneralReason"
              },
              {
                "type": "null"
              }
            ],
            "description": "General reason for steerable status"
          },
          "DHW": {
            "anyOf": [
              {
                "$ref": "#/components/schemas/ActionStatus"
              },
              {
                "type": "null"
              }
            ],
            "description": "Domestic Hot Water action status"
          },
          "room": {
            "anyOf": [
              {
                "$ref": "#/components/schemas/ActionStatus"
              },
              {
                "type": "null"
              }
            ],
            "description": "Room heating action status"
          },
          "has_cooling": {
            "anyOf": [
              {
                "type": "boolean"
              },
              {
                "type": "null"
              }
            ],
            "title": "Has Cooling",
            "description": "Whether the device has cooling capabilities"
          }
        },
        "type": "object",
        "title": "SteerableStatus",
        "description": "Steerable status model."
      },
      "ValidationError": {
        "properties": {
          "loc": {
            "items": {
              "anyOf": [
                {
                  "type": "string"
                },
                {
                  "type": "integer"
                }
              ]
            },
            "type": "array",
            "title": "Location"
          },
          "msg": {
            "type": "string",
            "title": "Message"
          },
          "type": {
            "type": "string",
            "title": "Error Type"
          }
        },
        "type": "object",
        "required": [
          "loc",
          "msg",
          "type"
        ],
        "title": "ValidationError"
      }
    },
    "securitySchemes": {
      "ApiKeyAuth": {
        "type": "apiKey",
        "in": "header",
        "name": "x-api-key",
        "description": "API Key authentication. Enter your API key in the format: YOUR_API_KEY"
      }
    }
  },
  "tags": [
    {
      "name": "Asset Info",
      "description": "API to get basic information about your assets."
    },
    {
      "name": "Device Consumption",
      "description": "API to get consumption data of your devices."
    },
    {
      "name": "Thermal Control",
      "description": "API for thermal control specific endpoints."
    },
    {
      "name": "User Management",
      "description": "API endpoints to manage users and their data."
    }
  ],
  "security": [
    {
      "ApiKeyAuth": []
    }
  ],
  "servers": [
    {
      "url": "https://api.nox.energy",
      "description": "Production Server"
    }
  ]
}